name: Auto tag new version

on:
  push:
    branches:
      - master
    paths:
      - 'package.json'

jobs:
  add-tag:
    name: Add a tag on new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1    
      - name: Detect new version and publish a tag
        if: github.ref == 'refs/heads/master' && github.repository == 'abaplint/abaplint'
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          git --version
          jq --version
          LAST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          LAST_TAG=${LAST_TAG#v}
          CUR_VERSION=$(jq -r -c .version package.json)
          echo "Last tag: ${LAST_TAG}, Current version: ${CUR_VERSION}"
          [ "${LAST_TAG}" = "${CUR_VERSION}" ] && echo "Version change was not detected, exiting..." && exit 0
          echo "Version change detected"
          [ -n "${GITHUB_TOKEN}" ] || echo "GITHUB_TOKEN is undefined"
          [ -n "${GITHUB_TOKEN}" ] || exit 1
          AUTH_HEADER="Authorization: token ${GITHUB_TOKEN}"
          API_ENDPOINT="https://api.github.com/repos/${GITHUB_REPOSITORY}/git/refs"
          API_REQUEST="{ \"ref\": \"refs/tags/v$CUR_VERSION\", \"sha\": \"$GITHUB_SHA\" }"
          echo "api endpoint: $API_ENDPOINT"
          echo "api request:  $API_REQUEST"
          echo "Publishing a new tag ..."
          curl -s -X POST $API_ENDPOINT -H "$AUTH_HEADER" -d "$API_REQUEST"
